version: "3.3"

services:

  app:
    tty: true
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - 8080

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432
